//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace piano.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("piano.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream a {
            get {
                return ResourceManager.GetStream("a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream a_ {
            get {
                return ResourceManager.GetStream("a_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream a_1 {
            get {
                return ResourceManager.GetStream("a_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream a1 {
            get {
                return ResourceManager.GetStream("a1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream c_1 {
            get {
                return ResourceManager.GetStream("c_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream c_2 {
            get {
                return ResourceManager.GetStream("c_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream c1 {
            get {
                return ResourceManager.GetStream("c1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream c2 {
            get {
                return ResourceManager.GetStream("c2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream d_1 {
            get {
                return ResourceManager.GetStream("d_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream d_2 {
            get {
                return ResourceManager.GetStream("d_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream d1 {
            get {
                return ResourceManager.GetStream("d1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream d2 {
            get {
                return ResourceManager.GetStream("d2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream e1 {
            get {
                return ResourceManager.GetStream("e1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream e2 {
            get {
                return ResourceManager.GetStream("e2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream f_1 {
            get {
                return ResourceManager.GetStream("f_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream f1 {
            get {
                return ResourceManager.GetStream("f1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E2D_2E2D_2E2H1D2C2A1 C1E1A1H1 E1G_1H1C2 E1E2D_2E2D_2E2H1D2C2A1 C1E1A1H1 E1C2H1A1.
        /// </summary>
        internal static string Fur_Elise {
            get {
                return ResourceManager.GetString("Fur Elise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream g_ {
            get {
                return ResourceManager.GetStream("g_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream g_1 {
            get {
                return ResourceManager.GetStream("g_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream g1 {
            get {
                return ResourceManager.GetStream("g1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream h {
            get {
                return ResourceManager.GetStream("h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream h1 {
            get {
                return ResourceManager.GetStream("h1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C1    G1D_2 G1 C1   G1D_2 G1 C1   G1D_2 G1 C1     C2 H1 A_1A_1A_1A1 G_1 G_1 G1G1F_1 F1 D_1 D1D_1F1 D_1 D1    C2 H1 A_1A_1A_1A1 G_1 G1G1 G1F_1 F1 D_1 D1 C1D1D_1 D1 C1    C2 H1 A_1A_1A_1A1 G_1 G1G1 G1F_1 F1 D_1 D1D_1F1 D_1 D1    C2 H1 A_1A_1A_1A1 G_1 G1G1 G1F_1 F1 D_1 D1 C1D1D_1 D1 C1   G1C1 D1 E1   G1E1 D1 C1  D1E1 F1 G1G1G1G1A1 G1 F1   A1D1 E1 F1   A1F1 E1 D1  E1F1 G1 A1A1A1A1H1 A1 G1  G1C2 D2 E2   G1E1 D1 C1  D1E1 F1 G1G1G1G1C2 H1 F1  A1D2 E2 C1  A1F1 E1 D1  E1F1 G1 H1   E2    D2 C2  G1E2 G1  C2  G1 E2 G1  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Habanera {
            get {
                return ResourceManager.GetString("Habanera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C2C2C2C2 C2H1 G1      C2C2C2C2 C2H1 G1 G1G1 G1 A1F_1A1C2H1A1H1G1       C2C2C2C2 C2H1 G1 G1G1 G1 A1F_1A1C2H1A1H1G1       C2C2 C2C2 H1G1 G1G1 G1 A1 F_1A1 C2 H1 H1 G1 E1 D1   G1   E1   F_1 F_1     G1    E1   F_1 F_1      H1     G1   A1 A1    H1   G1   A1 A1 D2C2 H1A1G1G1G1.
        /// </summary>
        internal static string La_Bamba {
            get {
                return ResourceManager.GetString("La Bamba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1
        ///2
        ///.
        /// </summary>
        internal static string levels {
            get {
                return ResourceManager.GetString("levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mainmanji {
            get {
                object obj = ResourceManager.GetObject("mainmanji", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mainveci {
            get {
                object obj = ResourceManager.GetObject("mainveci", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap menu {
            get {
                object obj = ResourceManager.GetObject("menu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap piano {
            get {
                object obj = ResourceManager.GetObject("piano", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap plus {
            get {
                object obj = ResourceManager.GetObject("plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap puzzle {
            get {
                object obj = ResourceManager.GetObject("puzzle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H1C2H1A1H1C2 A1 E1 C2H1 G1 H1C2H1A1H1C2 G1E1 C2H1 G1 H1C2H1A1G1F1C2 C2C2F1C2 C2C2 H1 C2H1C2D2E2E2H1 C2H1C2H1A1 A1A1.
        /// </summary>
        internal static string Seniorita {
            get {
                return ResourceManager.GetString("Seniorita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream silence {
            get {
                return ResourceManager.GetStream("silence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap star {
            get {
                object obj = ResourceManager.GetObject("star", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G1    C1D1D_1F1G1   D_1G1   D_1G1   C1D_1C1G_D_1C1     F1D_1D1G1    C1D1D_1F1G1   D_1G1   D_1G1   C1D_1C1G_D_1C1       C1D1 D_1 F1 G1G_1A_1  G_1G1 G_1A_1C2  A_1G_1 A_1C2D2  C2G1D_1D1C1G1    C1D1D_1F1G1   D_1G1   D_1G1   C1D_1C1G_D_1C1.
        /// </summary>
        internal static string swanlake {
            get {
                return ResourceManager.GetString("swanlake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C1C1G1G1A1A1G1 F1F1E1E1D1D1C1  G1G1F1F1E1E1D1 G1G1F1F1E1E1D1  C1C1G1G1A1A1G1 F1F1E1E1D1D1C1.
        /// </summary>
        internal static string Twinkle_Twinkle {
            get {
                return ResourceManager.GetString("Twinkle Twinkle", resourceCulture);
            }
        }
    }
}
